import "./globals.css";

export const metadata = {
    title: "Raphael Ezeigwe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-slate-900 md:h-screen md:overflow-hidden flex justify-center lg:px-0 px-4 lg:py-28 py-12 text-slate-400">{children}</body>
        </html>
    );
}
