import "./globals.css";

export const metadata = {
    title: "Raphael Ezeigwe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="text-gray-900">{children}</body>
        </html>
    );
}
