import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata = {
    title: "Raphael Ezeigwe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="text-gray-900">
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
